[tool.robotpy-build.metadata]
name = "robotpy-romi"
description = "Binary wrapper for WPILib Romi Vendor library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-romi"
license = "BSD-3-Clause"
install_requires = [
    "wpilib~=2023.4.3"
]


[build-system]
requires = [
    "robotpy-build<2024.0.0,>=2023.1.1",
    "wpilib~=2023.4.3"
]

[tool.robotpy-build]
base_package = "romi"

[tool.robotpy-build.wrappers."romi"]
name = "romi"
sources = ["romi/src/main.cpp"]
generation_data = "gen"
depends = [
    "wpilib_core", "wpilibc_interfaces", "wpilibc",
    "wpimath_cpp", "wpimath_geometry",
    "wpiHal", "wpiutil", "ntcore",
]

[tool.robotpy-build.wrappers."romi".autogen_headers]
# frc/romi
OnBoardIO = "frc/romi/OnBoardIO.h"
RomiGyro = "frc/romi/RomiGyro.h"
RomiMotor = "frc/romi/RomiMotor.h"

[tool.robotpy-build.wrappers."romi".maven_lib_download]
artifact_id = "romi-vendordep-cpp"
group_id = "edu.wpi.first.romi"
repo_url = "https://frcmaven.wpi.edu/artifactory/development"
version = "2023.4.2"
libs = ["Romi"]


